apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- with .Values.readReplicas.persistence }}
  name: {{ .existingClaim }}
  namespace: {{ .existingClaimNamespace }}
spec:
  accessModes: |-
    {{- range .accessModes }}
    - {{ . }}
    {{- end }}
  storageClassName: {{ .storageClass }}
  resources:
    requests:
      storage: {{ .size }}
  {{- end }}
