apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-apps
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - namespace: kube-system
        app-name: traefik
        path: 00-traefik
      - namespace: cert-manager
        app-name: cert-manager
        path: 01-cert-manager
      - namespace: invidious
        app-name: invidious
        path: 02-invidious
      - namespace: privatebin
        app-name: privatebin
        path: 03-privatebin
      - namespace: dialogue-extractor
        app-name: dialogue-extractor
        path: 04-dialogue-extractor
  template:      
    metadata:
      name: '{{app-name}}'
    spec:
      # The project the application belongs to.
      project: default

      # Source of the application manifests
      source:
        repoURL: git@github.com:carloseabade/k3s-cluster.git
        targetRevision: HEAD
        path: ./my-apps/{{path}}
      
      # Destination cluster and namespace to deploy the application
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'

      # Sync policy
      syncPolicy:
        syncOptions:
          - CreateNamespace=true  
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
