apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-video
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: carloseabade@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-video
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          ingressTemplate:
            metadata:
              annotations:
                kubernetes.io/ingress.class: traefik
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-video
  namespace: invidious
spec:
  secretName: letsencrypt-video
  issuerRef:
    name: letsencrypt-video
    kind: ClusterIssuer
  dnsNames:
  - video.abade.xyz
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-permanent
  namespace : invidious
spec:
  redirectScheme:
    permanent: true
    scheme: https
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-invidious
  namespace: invidious
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host("video.abade.xyz")
    services:
    - kind: Service
      name: invidious-invidious
      port: 3000
    middlewares:
    - name: redirect-permanent
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-invidious-secure
  namespace: invidious
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host("video.abade.xyz")
    services:
    - kind: Service
      name: invidious-invidious
      port: 3000
  tls:
    secretName: letsencrypt-video
